version: 0.2

phases:
  install:
    commands:
      # Check Java installations
      - ls /usr/lib/jvm/
      # Add Java 17 to alternatives if not already configured
      - alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/java 2
      - alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/javac 2
      # Set Java 17 as the default
      - alternatives --set java /usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/java
      - alternatives --set javac /usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/javac
      - echo Checking Java and Gradle versions
      - java -version
      - chmod +x ./gradlew
      - ./gradlew -v

  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
