name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.0.0"
    
    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform Configuration
      run: terraform validate

    - name: Plan Terraform Changes
      run: terraform plan -input=false -out=tfplan

    - name: Apply Terraform Changes
      run: terraform apply -input=false tfplan
      env:
        TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        TF_VAR_ami_id: ${{ secrets.AMI_ID }}
        TF_VAR_instance_type: ${{ secrets.INSTANCE_TYPE }}
        TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
